#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=1:00:00
#PBS -N app-sift2-connectome-generation
#PBS -V

set -e

time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./generate-connectome.sh

time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./generate-final-connectomes.py

