#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=1:30:00
#PBS -N app-sift2-connectome-generation
#PBS -V

set -e

# check if both labels and weights datatype. if so, need to extract only the streamlines that are 1 in labels. fastest way is with python3
weights=`jq -r '.weights' config.json`
labels=`jq -r '.labels' config.json`

if [ -f ${weights} ] && [ -f ${labels} ]; then
	time singularity exec -e docker://brainlife/dipy:1.4.0 ./extract_streamline_weights.py
fi

# generate connectomes
time singularity exec -e docker://brainlife/mrtrix3:3.0.3 ./generate-connectomes.sh

# update assignments file to match our labels datatype
[ ! -d assignments ] && mkdir -p assignments
[ ! -f assignments/index.json ] && echo "generating assignments labels datatype" && time singularity exec -e docker://brainlife/dipy:1.4.0 ./update_assignments.py


# generate networkneuro datatype
# [ ! -d netneuro ] && mkdir -p netneuro netneuro/output netneuro/surfaces netneuro/roipairs && cp -v ./connectomes/* ./netneuro/output/
# [ ! -f netneuro/roipairs/index.json ] && time singularity exec -e docker://brainlife/dipy:1.4.0 ./generate_networkneuro.py
#
# # generate vtks of parc
# [ ! -f netneuro/surfaces/index.json ] && time singularity exec -e docker://brainlife/pythonvtk:1.1 ./parc2vtk.py

# generate network datatypes
#SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://filsilva/cxnetwork:0.2.0 ./conmat2network.py

if [ ! -f ./connectomes/density.csv ]; then
	echo "something failed. check derivatives"
else
	echo "connectome generation completed"
	rm -rf *.mif *.txt
	mkdir -p output
	mv connectomes output/output/
	# cp ./netneuro/surfaces/index.json ./netneuro/labels.json
fi
